# Generated by Django 6.0 on 2026-02-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название анкеты')),
                ('survey_type', models.CharField(default='custom', max_length=50, verbose_name='Тип анкеты')),
                ('state_json', models.JSONField(blank=True, null=True, verbose_name='Структура анкеты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_json', models.JSONField(verbose_name='Ответы пользователя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.survey', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Ответ на анкету',
                'verbose_name_plural': 'Ответы на анкеты',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
