# Generated by Django 6.0 on 2026-03-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_survey_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_edit_after_submit',
            field=models.BooleanField(default=False, verbose_name='Разрешить изменения после отправки'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание анкеты'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='survey',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок'),
        ),
        migrations.AddField(
            model_name='survey',
            name='response_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум ответов'),
        ),
        migrations.AddField(
            model_name='survey',
            name='response_type',
            field=models.CharField(choices=[('unlimited', 'Неограниченное'), ('limited', 'Ограниченное количество'), ('date_limit', 'До определённой даты')], default='unlimited', max_length=20, verbose_name='Ограничение ответов'),
        ),
        migrations.AddField(
            model_name='survey',
            name='show_progress_bar',
            field=models.BooleanField(default=True, verbose_name='Показывать прогресс'),
        ),
        migrations.AddField(
            model_name='survey',
            name='show_question_numbers',
            field=models.BooleanField(default=True, verbose_name='Показывать номера вопросов'),
        ),
        migrations.AddField(
            model_name='survey',
            name='shuffle_questions',
            field=models.BooleanField(default=False, verbose_name='Перемешивать вопросы'),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='survey',
            name='visibility',
            field=models.CharField(choices=[('private', 'Приватная'), ('link', 'По ссылке'), ('public', 'Публичная')], default='link', max_length=20, verbose_name='Видимость'),
        ),
        migrations.CreateModel(
            name='SurveyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='Токен ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='polls.survey', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Ссылка на анкету',
                'verbose_name_plural': 'Ссылки на анкеты',
            },
        ),
    ]
